server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.33.43/tms_db?useSSL=false&serverTimezone=Asia/Shanghai
    username: tms_db_user
    password: F&qw7DE@xe
    # 连接池配置
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 30
      ######Druid监控配置######
      web-stat-filter:
        enabled: true
        #哪些资源配置监控：主要只静态资源和监控地址本身
        #exclusions: *.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*
      stat-view-servlet:
        #IP 白名单
        allow: 127.0.0.1
        #IP 黑名单
        #deny: 192.168.0.101
        #监控地址,默认 /druid/*
        url-pattern: /druid/*
        login-username: jieshi
        login-password: jieshii333
  redis:
    host: qadb-int.xiaozipu.cn
    port: 6379
    password: "PC8hXD76Vn3vJNye"
    database: 16
    #连接超时时间
    timeout: 1800ms
    lettuce:
      pool:
        #连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        #连接池中的最大空闲连接 默认 8
        max-idle: 8
        #连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1ms
        #连接池中的最小空闲连接 默认 0
        min-idle: 0